version: "3.7"

services:
  core:
    container_name: backend
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - ./core:/core
    command: ["python", "manage.py", "runserver", "0.0.0.0:8002"]
    restart: on-failure