version: "3.7"

services:
  core:
    container_name: backend
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - ./core:/core
    command: ["python", "manage.py", "runserver",  "0.0.0.0:8002"]
    environment:
      - DB_HOST=db
      - DB_NAME=core
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - 5435:5433
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    restart: on-failure